runtime: python38

instance_class: F1

env_variables:
  MYSQL_USER: 'root'  ## ??
  MYSQL_PASSWORD: 'saltyfish411'   ##<fill password>
  MYSQL_DB: 'musicDB'
  MYSQL_HOST: '173.255.116.10' ## ??
  CLOUD_SQL_CONNECTION_NAME: 'music-explorer-307006:us-central1:music-sql'

# Local Instance


# handlers:
# # - url: /script
# #   static_dir: static/script

# - url: /styles
#   static_dir: static/styles